apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169633388
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169633388
    app.kubernetes.io/part-of: test-app-169633388
  name: java-quarkus-169633388
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169633388
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169633388
    spec:
      containers:
      - image: quay.io/hacdev/fkusqjil-tenant/test-app-169633388/java-quarkus-169633388@sha256:f0b985f52a10efa431a0fa5260b7913b54029b713e7d18ac733242c852448018
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
